In [76]:
import pandas as pd
import glob

In [77]:
# folders are the databases folders, there should be a folder for each database in use in the current repo directory

folders = glob.glob('???')
pivots_o = []
pivots_f = []
pivots_g = []

In [78]:
# pivots are the files for normalized csv data that were generated before

for f in folders :
    pivots_o += glob.glob(f + '/' + 'pivot_o_normalized.csv')
    pivots_f += glob.glob(f + '/' + 'pivot_f_normalized.csv')
    pivots_g += glob.glob(f + '/' + 'pivot_g_normalized.csv')

In [116]:
# displaying list of normalized pivot tables from all databases directories

pivots_g

['t2d/pivot_g_normalized.csv',
 'ibd/pivot_g_normalized.csv',
 'ptb/pivot_g_normalized.csv',
 'AGP/pivot_g_normalized.csv']

In [91]:
frames_o = []
frames_f = []
frames_g = []

In [92]:
# adding all the normalized data to a list of frames for each taxonomic level (one database for each list node)

for p in pivots_o :
    frames_o.append(pd.read_csv(p, sep = ';'))
for p in pivots_f :
    frames_f.append(pd.read_csv(p, sep = ';'))
for p in pivots_g :
    frames_g.append(pd.read_csv(p, sep = ';'))

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [119]:
frames_g[3]

,Unnamed: 0,g__,g__1-68,g__5-7N15,g__A17,g__A55_D21,g__AF12,g__Abiotrophia,g__Acanthamoeba,g__Acetobacter,...,g__Yaniella,g__Yersinia,g__Zoogloea,g__cc_115,g__gut,g__nsmpVI18,g__p-75-a5,g__ph2,g__rc4-4,g__vadinCA11
0,10317.000001000,0.155121,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
1,10317.000001001,0.468978,0.000294,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000073,0.0,0.0,0.0,0.000000,0.000000,0.0
2,10317.000001002,0.138099,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
3,10317.000001004,0.277839,0.000439,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
4,10317.000001008,0.045823,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9506,10317,0.173995,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.001297,0.000000,0.0
9507,10317,0.192002,0.000000,0.0,0.0,0.0,0.0,0.000418,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
9508,10317,0.131405,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
9509,10317,0.198993,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
9510,10317,0.157426,0.000640,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000246,0.000689,0.0

In [128]:
# merging all the lists to single dataframes
# columns are the union of columns of the frames from each database, sorted in alphabetical order
# note that now rows are also sorted alphabetically, so some of the databases are not stored sequentially

key= frames_o[0].columns[0]
result_o = frames_o[0]
for df_o in frames_o[1:4] :
    result_o = pd.merge(result_o, df_o, how = 'outer', sort=True)
    
key= frames_f[0].columns[0]
result_f = frames_f[0]
for df_f in frames_f[1:4] :
    result_f = pd.merge(result_f, df_f, how = 'outer', sort=True)
    
key= frames_g[0].columns[0]
result_g = frames_g[0]
for df_g in frames_g[1:4] :
    result_g = pd.merge(result_g, df_g, how = 'outer', sort=True)

In [132]:
result_g

,Unnamed: 0,g__,g__02d06,g__1-68,g__Abiotrophia,g__Acetobacter,g__Acidaminococcus,g__Acidovorax,g__Acinetobacter,g__Actinobacillus,...,g__Winogradskyella,g__Wohlfahrtiimonas,g__Wolbachia,g__Xanthobacter,g__Xylanimicrobium,g__Yersinia,g__Zoogloea,g__gut,g__nsmpVI18,g__vadinCA11
0,10317,0.172942,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10317,0.210410,0.0,0.000588,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10317,0.288716,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10317,0.416667,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10317,0.482564,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14093,MSM5LLIO,0.187640,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14094,MSM5LLIQ,0.403338,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14095,MSM5ZOJY,0.523932,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14096,MSM633FF,0.153703,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14097,otu_table,0.433337,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [131]:
# filling the missing data with zeros (replacing None values created when new columns were added  by 0)

result_o.fillna(0, inplace = True)
result_f.fillna(0, inplace = True)
result_g.fillna(0, inplace = True)

In [134]:
# storaging the merged dataframes to the csv tables

result_o.to_csv('pivot_o.csv', sep=';', index=False)
result_f.to_csv('pivot_f.csv', sep=';', index=False)
result_g.to_csv('pivot_g.csv', sep=';', index=False)