In [1]:
import pandas as pd

In [2]:
# read the data from pivot tables to data frames

df_o = pd.read_csv('pivot_o.csv')
df_f = pd.read_csv('pivot_f.csv')
df_g = pd.read_csv('pivot_g.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df_g

,Unnamed: 0,g__,g__1-68,g__5-7N15,g__A17,g__A55_D21,g__AF12,g__Abiotrophia,g__Acanthamoeba,g__Acetobacter,...,g__cc_115,g__gut,g__nsmpVI18,g__p-75-a5,g__ph2,g__rc4-4,g__vadinCA11,g__[Eubacterium],g__[Prevotella],g__[Ruminococcus]
0,10317.000001000,0.155121,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.009775
1,10317.000001001,0.468978,0.000294,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000073,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.003706
2,10317.000001002,0.138099,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.001219,0.000000,0.004062
3,10317.000001004,0.277839,0.000439,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000988,0.000000,0.014606
4,10317.000001008,0.045823,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.016203,0.000000,0.014177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9506,10317,0.173995,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.001297,0.000000,0.0,0.001586,0.000000,0.018115
9507,10317,0.192002,0.000000,0.0,0.0,0.0,0.0,0.000418,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000557,0.000000,0.011913
9508,10317,0.131405,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.005577
9509,10317,0.198993,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.017817,0.000000,0.007630
9510,10317,0.157426,0.000640,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000246,0.000689,0.0,0.016382,0.000295,0.007527

In [4]:
# renaming columns to remove '[' and ']' symbols from column names

df_o.rename(columns=lambda x: x.replace('[','').replace(']',''), inplace=True)
df_f.rename(columns=lambda x: x.replace('[','').replace(']',''), inplace=True)
df_g.rename(columns=lambda x: x.replace('[','').replace(']',''), inplace=True)

In [5]:
# creating new dataframes with merged identical column names (created after removing the brackets)

df_o_norm = df_o.groupby(level=0, axis=1).sum()
df_f_norm = df_f.groupby(level=0, axis=1).sum()
df_g_norm = df_g.groupby(level=0, axis=1).sum()

In [6]:
df_g_norm.iloc[:,1:]

,g__,g__1-68,g__5-7N15,g__A17,g__A55_D21,g__AF12,g__Abiotrophia,g__Acanthamoeba,g__Acetobacter,g__Acetobacterium,...,g__Yaniella,g__Yersinia,g__Zoogloea,g__cc_115,g__gut,g__nsmpVI18,g__p-75-a5,g__ph2,g__rc4-4,g__vadinCA11
0,0.155121,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
1,0.468978,0.000294,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000073,0.0,0.0,0.0,0.000000,0.000000,0.0
2,0.138099,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
3,0.277839,0.000439,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
4,0.045823,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9506,0.173995,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.001297,0.000000,0.0
9507,0.192002,0.000000,0.0,0.0,0.0,0.0,0.000418,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
9508,0.131405,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
9509,0.198993,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
9510,0.157426,0.000640,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000246,0.000689,0.0

In [7]:
# normilizing the data across each row

df_o_norm.iloc[:,1:] = df_o_norm.iloc[:,1:].div(df_o_norm.sum(axis=1), axis=0)
df_f_norm.iloc[:,1:] = df_f_norm.iloc[:,1:].div(df_f_norm.sum(axis=1), axis=0)
df_g_norm.iloc[:,1:] = df_g_norm.iloc[:,1:].div(df_g_norm.sum(axis=1), axis=0)

In [8]:
df_o_norm

,Unnamed: 0,o__,o__0319-7L14,o__A31,o__A89,o__AKIW781,o__AKYG885,o__Acholeplasmatales,o__Acidimicrobiales,o__Acidobacteriales,...,o__Victivallales,o__WCHB1-41,o__WD2101,o__Xanthomonadales,o__YLA114,o__YS2,o__Z20,o__envOPS12,o__iii1-15,o__mle1-48
0,10317.000001000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
1,10317.000001001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
2,10317.000001002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
3,10317.000001004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.001318,0.0,0.0,0.0,0.0
4,10317.000001008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9506,10317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000192,0.0,0.000000,0.0,0.0,0.0,0.0
9507,10317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000139,0.0,0.000000,0.0,0.0,0.0,0.0
9508,10317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
9509,10317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0
9510,10317,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0

In [9]:
# sorting the column names in the alphabet order

df_o_norm.sort_index(axis=1, inplace=True)
df_f_norm.sort_index(axis=1, inplace=True)
df_g_norm.sort_index(axis=1, inplace=True)

In [10]:
# storage normalized data with removed brackets to new csv files

df_o_norm.to_csv('pivot_o_normalized.csv', sep=';', index=False)
df_f_norm.to_csv('pivot_f_normalized.csv', sep=';', index=False)
df_g_norm.to_csv('pivot_g_normalized.csv', sep=';', index=False)